@extends('layouts.app')

@section('title', 'Documentation - InApp Inventory Dashboard')

@section('content')
<div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-3">
            <div class="">
              <h1 class="fs-3 mb-1">Documentation</h1>
             <p>
          This documentation will guide you through the setup and usage of the InApp Inventory Dashboard template.
        </p>
            </div>

          </div>
        </div>
      </div>

        <div class="row">
            <div class="col-12">
                <div class="">
    <div class="">



      <!-- Prerequisites -->
      <div class="mb-4">
        <div class="mb-2">
        <h2 class="h5 mb-1">Prerequisites</h2>
        <p>Before you begin, ensure you have the following installed:</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item ps-0">Node.js (v14 or higher)</li>
          <li class="list-group-item ps-0">npm or yarn package manager</li>
          <li class="list-group-item ps-0">[Any other specific tools/dependencies]</li>
        </ul>
      </div>

      <!-- Installation -->
      <div class="mb-4">
        <h2 class="h5 mb-2">Installation</h2>
        <ol class="list-group list-group-numbered list-group-flush">
          <li class="list-group-item ps-0" >Clone the repository or download the template</li>
          <li class="list-group-item ps-0">Navigate to the project directory</li>
          <li class="list-group-item ps-0">
            Install dependencies:
            <pre class="bg-light border rounded p-3 mt-2"><code>npm install</code></pre>
          </li>
        </ol>
      </div>



      <!-- Usage -->
      <div class="mb-6">
        <h2 class="h5 mb-2">Run the app</h2>
        <p>To start the development server:</p>
        <pre class="bg-light border rounded p-3"><code>npm run dev</code></pre>
      </div>
    <!-- Next Steps -->
      <div class="mb-4">
        <h2 class="h5 mb-2">Next Steps</h2>
        <ol class="list-group list-group-numbered list-group-flush">
          <li class="list-group-item ps-0">Review the template sources in <code>resources/js/template/</code> and <code>resources/scss/template/</code></li>
          <li class="list-group-item ps-0">Customize components according to your needs</li>
          <li class="list-group-item ps-0">
            Build for production:
            <pre class="bg-light border rounded p-3 mt-4"><code>npm run build</code></pre>
          </li>
        </ol>
      </div>

      <!-- Project Structure -->
      <div class="mb-4">
        <h2 class="h5 mb-0">Project Structure</h2>
        <pre>
     <code>
StockPilot/
├── public/
│   ├── assets/
│   │   └── images/     # Template images and icons
│   └── build/          # Compiled assets generated by Vite
├── resources/
│   ├── js/template/    # Template JS source (Vite)
│   ├── scss/template/  # Template SCSS source (Vite)
│   └── views/
│   ├── layouts/        # app.blade.php and auth.blade.php
│   ├── partials/       # header, sidebar, scripts, styles, footer
│   ├── pages/          # dashboard, inventory, reports, docs
│   └── auth/           # login and register
├── routes/web.php      # Page routes
└── vite.config.js      # Standard Laravel Vite input
     </code>
     </pre>
      </div>


      <!-- Support -->
      <div class="mb-2">
        <h2 class="h5">Support</h2>
        <p>
          For issues or questions, please refer to the documentation or create an issue in the repository. Also you can contact
          us at <a href="#!" class="text-primary">CodesCandy</a>.
        </p>
      </div>

    </div>
  </div>

            </div>
            </div>
    </div>
@endsection

